### ISSUE TITLE
📝 文档改善 - 欢迎大家来贡献实用有趣的角色信息！！

### ISSUE THREAD

**Issue by Leizhenpeng** [Leizhenpeng/feishu-chatgpt#136]
# 文档改善建议 📝

- 可在此处提交你认为不错的角色预设, 注意保持格式一致。
- PR时的tag暂时集中在 [ "日常办公",  "生活助手" ,"代码专家", "文案撰写"]
- 更多点子可参考我另一个参与的项目: https://open-gpt.app/
- 不用担心列表爆炸，后续会支持角色搜索，尽情发挥想象力吧！

## 格式参考

``` yaml
- title: 回复老板
  content: 请用 5 种委婉的借口向领导表达后面的内容
  example:  不想加班
  author: 小叉Ray
  tags:
    - 日常办公
    - 文案撰写
```

### PC
<img src='https://user-images.githubusercontent.com/50035229/228092540-bb9c74de-fccb-4d07-9797-f3fe1fb3705a.png' alt='角色列表' width='600'/>

## MOBI
<img src='https://user-images.githubusercontent.com/50035229/228095808-ed6f9b7a-2a31-49cd-92f2-69b437d96c0c.png' alt='角色列表' width='300'/>
